# Generated by Django 5.0.1 on 2024-03-18 19:07

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "from_user",
                    models.CharField(max_length=100, verbose_name="from user"),
                ),
                ("confirmations", models.IntegerField(verbose_name="confirmations")),
                ("value", models.CharField(max_length=100, verbose_name="value")),
                (
                    "adopted_pet_slug",
                    models.CharField(max_length=100, verbose_name="adopted slug"),
                ),
                (
                    "payment_options",
                    models.CharField(
                        choices=[("STRIPE", "stripe"), ("ETHEREUM", "ethereum")],
                        max_length=100,
                        null=True,
                        verbose_name="payment options",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
            },
        ),
    ]
