# Generated by Django 5.0.1 on 2024-03-19 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0002_alter_transaction_adopted_pet_slug_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="confirmations",
        ),
    ]
