# Generated by Django 5.0.1 on 2024-03-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0003_remove_transaction_confirmations"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="confirmations",
            field=models.IntegerField(null=True, verbose_name="confirmations"),
        ),
    ]
