# Generated by Django 5.0.1 on 2024-03-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0004_transaction_confirmations"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="session",
            field=models.CharField(max_length=100, null=True, verbose_name="session"),
        ),
    ]
