# Generated by Django 5.0.1 on 2024-03-19 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0005_transaction_session"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="session",
            new_name="session_id",
        ),
    ]
