openapi: 3.0.3
info:
  title: Django DRF Ecommerce
  version: 1.0.0
  description: This project purpose creating ecommerce api for business company
paths:
  /orders/create-checkout-session/:
    post:
      operationId: orders_create_checkout_session_create
      description: Order
      tags:
      - orders
      security:
      - jwtAuth: []
      - cookieAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /pets/:
    get:
      operationId: pets_retrieve
      description: |-
        Retrieve a list of all pets.

        Parameters:
            request (HttpRequest): The HTTP request object.

        Returns:
            Response: A response object containing the serialized data of all pets and the HTTP status code.
      tags:
      - pets
      security:
      - jwtAuth: []
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
          description: ''
    post:
      operationId: pets_create
      description: |-
        Create a new pet.

        Parameters:
            request (HttpRequest): The HTTP request object.
            format (str): The format of the request data (optional).

        Returns:
            Response: A response object containing the serialized data of the created pet and the HTTP status code.
      tags:
      - pets
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Pet'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Pet'
        required: true
      security:
      - jwtAuth: []
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
          description: ''
    delete:
      operationId: pets_destroy
      description: |-
        Delete all pets.

        Parameters:
            request (HttpRequest): The HTTP request object.

        Returns:
            Response: A response object with no content and the HTTP status code indicating success.
      tags:
      - pets
      security:
      - jwtAuth: []
      - cookieAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /pets/{slug}/:
    get:
      operationId: pets_retrieve_2
      description: |-
        Retrieve details of a specific pet.

        Parameters:
            request (HttpRequest): The HTTP request object.
            slug (str): The slug of the pet.

        Returns:
            Response: A response object containing the serialized data of the pet if found, or an HTTP status code indicating not found.
      parameters:
      - in: path
        name: slug
        schema:
          type: string
        required: true
      tags:
      - pets
      security:
      - jwtAuth: []
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
          description: ''
    put:
      operationId: pets_update
      description: |-
        Update the details of a specific pet.

        Parameters:
            request (HttpRequest): The HTTP request object.
            slug (str): The slug of the pet.

        Returns:
            Response: A response object containing the serialized data of the updated pet if successful, or an HTTP status code indicating an error.
      parameters:
      - in: path
        name: slug
        schema:
          type: string
        required: true
      tags:
      - pets
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Pet'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Pet'
        required: true
      security:
      - jwtAuth: []
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
          description: ''
    delete:
      operationId: pets_destroy_2
      description: |-
        Delete a specific pet.

        Parameters:
            request (HttpRequest): The HTTP request object.
            slug (str): The slug of the pet.

        Returns:
            Response: A response object with no content and the HTTP status code indicating success or not found.
      parameters:
      - in: path
        name: slug
        schema:
          type: string
        required: true
      tags:
      - pets
      security:
      - jwtAuth: []
      - cookieAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /transactions/:
    get:
      operationId: transactions_retrieve
      tags:
      - transactions
      security:
      - jwtAuth: []
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
          description: ''
    post:
      operationId: transactions_create
      tags:
      - transactions
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transaction'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Transaction'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Transaction'
        required: true
      security:
      - jwtAuth: []
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
          description: ''
  /upload/image/:
    post:
      operationId: upload_image_create
      tags:
      - upload
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Upload'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Upload'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Upload'
        required: true
      security:
      - jwtAuth: []
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Upload'
          description: ''
  /users/:
    get:
      operationId: users_retrieve
      description: Get, Update user information
      tags:
      - users
      security:
      - jwtAuth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomUser'
          description: ''
    put:
      operationId: users_update
      description: Get, Update user information
      tags:
      - users
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomUser'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/CustomUser'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/CustomUser'
      security:
      - jwtAuth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomUser'
          description: ''
    patch:
      operationId: users_partial_update
      description: Get, Update user information
      tags:
      - users
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedCustomUser'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedCustomUser'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedCustomUser'
      security:
      - jwtAuth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomUser'
          description: ''
  /users/login/:
    post:
      operationId: users_login_create
      description: An endpoint to authenticate existing users using their email and
        password.
      tags:
      - users
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserLogin'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UserLogin'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UserLogin'
        required: true
      security:
      - jwtAuth: []
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserLogin'
          description: ''
  /users/logout/:
    post:
      operationId: users_logout_create
      description: An endpoint to logout users.
      tags:
      - users
      security:
      - jwtAuth: []
      - cookieAuth: []
      responses:
        '200':
          description: No response body
  /users/register/:
    post:
      operationId: users_register_create
      description: An endpoint for the client to create a new User.
      tags:
      - users
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegisteration'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UserRegisteration'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UserRegisteration'
        required: true
      security:
      - jwtAuth: []
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserRegisteration'
          description: ''
  /users/token/refresh/:
    post:
      operationId: users_token_refresh_create
      description: |-
        Takes a refresh type JSON web token and returns an access type JSON web
        token if the refresh token is valid.
      tags:
      - users
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenRefresh'
          description: ''
components:
  schemas:
    CustomUser:
      type: object
      description: Serializer class to serialize CustomUser model.
      properties:
        id:
          type: integer
          readOnly: true
        username:
          type: string
          nullable: true
          maxLength: 100
        email:
          type: string
          format: email
          nullable: true
          title: Email address
          maxLength: 254
        wallet_address:
          type: string
          nullable: true
          maxLength: 100
      required:
      - id
    GenderEnum:
      enum:
      - MALE
      - FEMALE
      - 'Neutered '
      - Spayed
      - Other
      type: string
      description: "* `MALE` - male\n* `FEMALE` - female\n* `Neutered ` - neutered\
        \ \n* `Spayed` - spayed\n* `Other` - other"
    PatchedCustomUser:
      type: object
      description: Serializer class to serialize CustomUser model.
      properties:
        id:
          type: integer
          readOnly: true
        username:
          type: string
          nullable: true
          maxLength: 100
        email:
          type: string
          format: email
          nullable: true
          title: Email address
          maxLength: 254
        wallet_address:
          type: string
          nullable: true
          maxLength: 100
    PaymentOptionsEnum:
      enum:
      - STRIPE
      - ETHEREUM
      type: string
      description: |-
        * `STRIPE` - stripe
        * `ETHEREUM` - ethereum
    Pet:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 50
        age:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
        breed:
          type: string
          maxLength: 50
        slug:
          type: string
          readOnly: true
          pattern: ^[-a-zA-Z0-9_]+$
        color:
          type: string
          pattern: ^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$
          maxLength: 25
        weight:
          type: number
          format: double
        gender:
          $ref: '#/components/schemas/GenderEnum'
        pet_photo_url:
          type: string
          format: uri
          title: Pet photo
          pattern: (?:png|jpg|jpeg)$
        pet_photo_link:
          type: string
          format: uri
          maxLength: 200
        location:
          type: string
          maxLength: 50
        city:
          type: string
          maxLength: 50
        status:
          type: boolean
        vaccinated:
          type: boolean
        price_currency:
          type: string
          readOnly: true
          nullable: true
        price:
          type: string
          format: decimal
          pattern: ^-?\d{0,12}(?:\.\d{0,2})?$
          nullable: true
        description:
          type: string
          maxLength: 150
      required:
      - age
      - breed
      - city
      - description
      - id
      - location
      - name
      - price_currency
      - slug
      - weight
    TokenRefresh:
      type: object
      properties:
        access:
          type: string
          readOnly: true
        refresh:
          type: string
      required:
      - access
      - refresh
    Transaction:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        from_user:
          type: string
        confirmations:
          type: string
        created:
          type: string
          format: date-time
          readOnly: true
        modified:
          type: string
          format: date-time
          readOnly: true
        value:
          type: string
          maxLength: 100
        adopted_pet_slug:
          type: string
          title: Adopted slug
          maxLength: 100
        payment_options:
          $ref: '#/components/schemas/PaymentOptionsEnum'
        session_id:
          type: string
          nullable: true
          title: Session
          maxLength: 100
      required:
      - adopted_pet_slug
      - confirmations
      - created
      - from_user
      - id
      - modified
      - payment_options
      - value
    Upload:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        upload_at:
          type: string
          format: date-time
          readOnly: true
        file:
          type: string
          format: uri
      required:
      - file
      - id
      - upload_at
    UserLogin:
      type: object
      description: Serializer class to authenticate users with email and password.
      properties:
        email:
          type: string
        password:
          type: string
          writeOnly: true
      required:
      - email
      - password
    UserRegisteration:
      type: object
      description: Serializer class to serialize registration requests and create
        a new user.
      properties:
        id:
          type: integer
          readOnly: true
        username:
          type: string
          nullable: true
          maxLength: 100
        email:
          type: string
          format: email
          nullable: true
          title: Email address
          maxLength: 254
        password:
          type: string
          writeOnly: true
          maxLength: 128
        wallet_address:
          type: string
          nullable: true
          maxLength: 100
      required:
      - id
      - password
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
