# Generated by Django 5.0.1 on 2024-03-22 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="username",
            field=models.CharField(max_length=100, null=True, verbose_name="Username"),
        ),
    ]
