# Generated by Django 5.0.1 on 2024-03-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_customuser_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                max_length=254, null=True, unique=True, verbose_name="Email address"
            ),
        ),
    ]
