# Generated by Django 5.0.1 on 2024-03-24 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_customuser_email"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
