# Generated by Django 5.0.1 on 2024-02-15 05:18

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, editable=False, unique=True, verbose_name="Slug"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="First name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Last name"
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Full name"
                    ),
                ),
                (
                    "profile_key",
                    django_extensions.db.fields.RandomCharField(
                        blank=True,
                        editable=False,
                        length=12,
                        unique=True,
                        verbose_name="Profile key",
                    ),
                ),
                (
                    "country",
                    models.CharField(blank=True, max_length=50, verbose_name="Country"),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="City"
                    ),
                ),
                (
                    "adress",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Adress"
                    ),
                ),
                (
                    "additional_information",
                    models.TextField(blank=True, verbose_name="Additional Information"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Is active"),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[("ADMIN", "admin"), ("GENERAL", "general")],
                        default="GENERAL",
                        max_length=20,
                        null=True,
                        verbose_name="Account type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "active"), ("INACTIVE", "inactive")],
                        default="INACTIVE",
                        max_length=20,
                        null=True,
                        verbose_name="Status",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("MALE", "male"), ("FEMALE", "female")],
                        max_length=20,
                        null=True,
                        verbose_name="Gender",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile",
                "verbose_name_plural": "Profiles",
            },
        ),
    ]
