# Generated by Django 5.0.1 on 2024-03-23 16:33

from django.db import migrations, models

import config.helpers


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="full_name",
        ),
        migrations.AddField(
            model_name="profile",
            name="wallet_address",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=100,
                null=True,
                unique=True,
                validators=[config.helpers.is_valid_wallet_address],
                verbose_name="Wallet address",
            ),
        ),
    ]
