# Generated by Django 5.0.1 on 2024-03-24 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0002_remove_profile_full_name_profile_wallet_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="wallet_address",
        ),
        migrations.AddField(
            model_name="profile",
            name="full_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Full name"
            ),
        ),
    ]
