# Generated by Django 5.0.1 on 2024-02-16 06:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0003_profile_profile_photo_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_photo_url",
            field=models.FileField(
                blank=True,
                upload_to="",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png", "jpg", "jpeg"]
                    )
                ],
                verbose_name="Profile photo",
            ),
        ),
    ]
