# Generated by Django 5.0.1 on 2024-02-16 07:16

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0004_alter_profile_profile_photo_url"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="profile",
            managers=[
                ("objects_active_qs", django.db.models.manager.Manager()),
            ],
        ),
    ]
