# Generated by Django 5.0.1 on 2024-02-16 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0005_alter_profile_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="profile",
            managers=[],
        ),
    ]
