# Generated by Django 5.0.1 on 2024-02-16 04:19

import colorfield.fields
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
                ("age", models.IntegerField(verbose_name="Age")),
                ("breed", models.CharField(max_length=50, verbose_name="Breed")),
                (
                    "color",
                    colorfield.fields.ColorField(
                        default="#FFFFFF", image_field=None, max_length=25, samples=None
                    ),
                ),
                ("weight", models.FloatField(verbose_name="Weight")),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("MALE", "male"),
                            ("FEMALE", "female"),
                            ("Neutered ", "neutered "),
                            ("Spayed", "spayed"),
                            ("Other", "other"),
                        ],
                        default="Other",
                        max_length=50,
                        verbose_name="Gender",
                    ),
                ),
                ("location", models.CharField(max_length=50, verbose_name="Location")),
                ("status", models.BooleanField(default=True, verbose_name="Status")),
                (
                    "vaccinated",
                    models.BooleanField(default=True, verbose_name="Vaccinated"),
                ),
                (
                    "description",
                    models.TextField(max_length=150, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Pet",
                "verbose_name_plural": "Pets",
                "ordering": ["-created"],
            },
        ),
    ]
