# Generated by Django 5.0.1 on 2024-02-17 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="city",
            field=models.CharField(default=1, max_length=50, verbose_name="City"),
            preserve_default=False,
        ),
    ]
