# Generated by Django 5.0.1 on 2024-02-16 06:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="pet_photo_url",
            field=models.FileField(
                default=1,
                upload_to="",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png", "jpg", "jpeg"]
                    )
                ],
                verbose_name="Pet photo",
            ),
            preserve_default=False,
        ),
    ]
