# Generated by Django 5.0.1 on 2024-02-15 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pet", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="gender",
            field=models.CharField(
                choices=[
                    ("MALE", "male"),
                    ("FEMALE", "female"),
                    ("Neutered ", "neutered "),
                    ("Spayed", "spayed"),
                    ("Other", "other"),
                ],
                default="Other",
                max_length=50,
                verbose_name="Gender",
            ),
        ),
    ]
