# Generated by Django 5.0.1 on 2024-02-17 21:14

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pet", "0002_pet_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="pet_key",
            field=django_extensions.db.fields.RandomCharField(
                blank=True,
                editable=False,
                length=12,
                unique=True,
                verbose_name="Pet key",
            ),
        ),
        migrations.AddField(
            model_name="pet",
            name="slug",
            field=models.SlugField(
                blank=True, editable=False, unique=True, verbose_name="Slug"
            ),
        ),
    ]
