# Generated by Django 5.0.1 on 2024-03-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="categories",
            field=models.ManyToManyField(
                null=True,
                related_name="posts_categories",
                to="posts.category",
                verbose_name="Categories",
            ),
        ),
    ]
