# Generated by Django 5.0.1 on 2024-03-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_alter_post_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="posts_categories",
                to="posts.category",
                verbose_name="Categories",
            ),
        ),
    ]
