# Generated by Django 5.0.1 on 2024-03-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0006_alter_post_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                max_length=100, null=True, unique=True, verbose_name="Category name"
            ),
        ),
    ]
