# Generated by Django 5.0.1 on 2024-03-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0007_alter_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(
                max_length=250, null=True, unique=True, verbose_name="Post title"
            ),
        ),
    ]
