name: Smart Contract Deploy
on:
  push:
    paths:
      - blockchain/**
      - .github/workflows/blockchain.yml
env:
  VITE_VUE_APP_API_URL: ""
jobs:
  deploy-development:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 20
    defaults:
      run:
        working-directory: blockchain/
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install NPM dependencies
        run: npm install --force
      - name: Run tests
        run: npm run test
      - name: Run tests coverage
        run: npm run coverage
      - name: Run ESLint Check Code Quality
        run: npm run lint
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
